# Generated by Django 5.2.5 on 2026-08-27 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('order_number', models.CharField(max_length=32, unique=True, verbose_name='Номер замовлення')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Ключ сесії')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('done', 'Виконано'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('payment_status', models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('failed', 'Помилка оплати')], default='pending', max_length=20, verbose_name='Статус оплати')),
                ('customer_name', models.CharField(max_length=255, verbose_name="Ім'я покупця")),
                ('customer_phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('np_city_name', models.CharField(blank=True, max_length=255, verbose_name='Місто (текст)')),
                ('np_warehouse_name', models.CharField(blank=True, max_length=255, verbose_name='Відділення (текст)')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума товарів')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='в т.ч. ПДВ')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='До сплати')),
                ('consent_gdpr', models.BooleanField(default=False, verbose_name='Згода на обробку ПД')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар покупця')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Назва (snapshot)')),
                ('weight_option_label', models.CharField(max_length=50, verbose_name='Фасування (snapshot)')),
                ('sku', models.CharField(max_length=64, verbose_name='Артикул (snapshot)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (snapshot)')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кількість')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума рядка')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Лог статусу замовлення',
                'verbose_name_plural': 'Логи статусів замовлень',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('provider', models.CharField(default='wayforpay', max_length=32, verbose_name='Провайдер')),
                ('order_reference', models.CharField(max_length=64, unique=True, verbose_name='orderReference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('currency', models.CharField(default='UAH', max_length=8, verbose_name='Валюта')),
                ('transaction_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='Статус транзакції')),
                ('signature_verified', models.BooleanField(default=False, verbose_name='Підпис перевірено')),
                ('raw_callback', models.JSONField(blank=True, null=True, verbose_name='Callback payload')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплати',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Ключ сесії')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('converted', 'Перетворено в замовлення'), ('abandoned', 'Покинутий')], default='active', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Кількість')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('weight_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productweightoption')),
            ],
            options={
                'verbose_name': 'Товар у кошику',
                'verbose_name_plural': 'Товари у кошику',
            },
        ),
    ]
