# Generated by Django 5.2.5 on 2026-08-27 13:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('pcs', 'шт'), ('pack', 'пач'), ('pkg', 'уп'), ('box', 'ящик')], default='pcs', max_length=10, verbose_name='Одиниця (snapshot)'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Для вагових товарів (кг) — дробове значення з кроком 0.1.', max_digits=8, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Кількість'),
        ),
    ]
