# Generated by Django 5.2.5 on 2026-08-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_orderitem_unit_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиція', 'verbose_name_plural': 'Склад замовлення'},
        ),
        migrations.AlterModelOptions(
            name='orderstatuslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запис статусу', 'verbose_name_plural': 'Історія статусів'},
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Покупець'),
        ),
        migrations.AlterField(
            model_name='order',
            name='np_city_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='np_warehouse_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Відділення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=32, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('failed', 'Помилка оплати')], default='pending', max_length=20, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(max_length=64, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('pcs', 'шт'), ('pack', 'пач'), ('pkg', 'уп'), ('box', 'ящик')], default='pcs', max_length=10, verbose_name='Одиниця'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight_option_label',
            field=models.CharField(max_length=50, verbose_name='Фасування'),
        ),
    ]
