services:
  backend:
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: config.settings.develop
