# Generated by Django 5.2.5 on 2026-08-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO title')),
                ('seo_title_uk', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO description')),
                ('seo_description_uk', models.TextField(blank=True, null=True, verbose_name='SEO description')),
                ('seo_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO description')),
                ('seo_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO H1')),
                ('seo_h1_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO H1')),
                ('seo_h1_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO H1')),
                ('seo_keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO keywords')),
                ('seo_keywords_uk', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO keywords')),
                ('seo_keywords_ru', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO keywords')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Зображення')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO title')),
                ('seo_title_uk', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO description')),
                ('seo_description_uk', models.TextField(blank=True, null=True, verbose_name='SEO description')),
                ('seo_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO description')),
                ('seo_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO H1')),
                ('seo_h1_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO H1')),
                ('seo_h1_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO H1')),
                ('seo_keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO keywords')),
                ('seo_keywords_uk', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO keywords')),
                ('seo_keywords_ru', models.CharField(blank=True, max_length=512, null=True, verbose_name='SEO keywords')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('is_available', models.BooleanField(default=True, help_text='Просте boolean — без точної кількості (клієнт підтвердив 3.3).', verbose_name='В наявності')),
                ('is_hit', models.BooleanField(default=False, help_text='Показ у блоці «Хіти продажу» на головній.', verbose_name='Хіт продажу')),
                ('is_new', models.BooleanField(default=False, help_text='Показ у блоці «Новинки» на головній.', verbose_name='Новинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товару',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductWeightOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('label', models.CharField(help_text='Напр. «500 г», «1 кг», «ящик 10 кг».', max_length=50, verbose_name='Фасування')),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('pcs', 'шт'), ('box', 'ящик')], default='kg', max_length=10, verbose_name='Одиниця')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна з ПДВ')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основний варіант')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_options', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Варіант фасування',
                'verbose_name_plural': 'Варіанти фасування',
                'ordering': ['sort_order', 'price'],
                'constraints': [models.UniqueConstraint(fields=('product', 'label'), name='unique_product_label')],
            },
        ),
    ]
