# Generated by Django 5.2.5 on 2026-08-27 13:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productweightoption',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Для вагових (кг) — мінімальна вага, напр. 0.3. Для штучних — мінімальна кількість, напр. 1 або 2.', max_digits=6, verbose_name='Мін. кількість замовлення'),
        ),
        migrations.AlterField(
            model_name='productweightoption',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Ціна за 1 одиницю з обраного «Одиниця» (за 1 кг, якщо кг; за 1 шт/пач/уп/ящик — якщо штучний).', max_digits=10, verbose_name='Ціна з ПДВ'),
        ),
        migrations.AlterField(
            model_name='productweightoption',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('pcs', 'шт'), ('pack', 'пач'), ('pkg', 'уп'), ('box', 'ящик')], default='kg', help_text='«кг» — ваговий товар: ціна за 1 кг, покупець обирає вагу з кроком 0.1 кг. «шт»/«пач»/«уп»/«ящик» — штучний товар: ціна за 1 одиницю, кількість цілими.', max_length=10, verbose_name='Одиниця'),
        ),
    ]
