# Generated by Django 5.2.5 on 2026-08-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productweightoption_min_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productweightoption',
            name='approx_unit_weight',
            field=models.CharField(blank=True, help_text='Для вагових товарів (кг) — довідкова вага однієї штуки/риби, напр. «≈ 300–400 г/шт» або «2–3 шт/кг». Показується поруч із вагою на картці й сторінці товару, щоб покупець розумів розмір. Порожнє поле — підказка не показується.', max_length=100, verbose_name='Орієнтовна вага 1 од.'),
        ),
    ]
