# Generated by Django 5.2.5 on 2026-08-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Про нас', 'verbose_name_plural': 'Про нас'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Звернення', 'verbose_name_plural': 'Звернення'},
        ),
        migrations.AlterModelOptions(
            name='contactspage',
            options={'verbose_name': 'Контакти', 'verbose_name_plural': 'Контакти'},
        ),
        migrations.AlterModelOptions(
            name='deliverypage',
            options={'verbose_name': 'Доставка і оплата', 'verbose_name_plural': 'Доставка і оплата'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Налаштування', 'verbose_name_plural': 'Налаштування'},
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='body_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='wholesale_link_url',
            field=models.URLField(default='https://rk-arctica.com.ua/', verbose_name='Посилання на опт'),
        ),
        migrations.AlterField(
            model_name='deliverypage',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='deliverypage',
            name='body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='deliverypage',
            name='body_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
