# Generated by Django 5.2.5 on 2026-08-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_admin_labels_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypage',
            options={'verbose_name': 'Конфіденційність', 'verbose_name_plural': 'Конфіденційність'},
        ),
    ]
