# Generated by Django 5.2.5 on 2026-08-28 11:25

import src.content.models_home
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_privacy_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('hero_title_line1', models.CharField(default='Риба яку ми', max_length=120, verbose_name='Hero: рядок 1 заголовка')),
                ('hero_title_line1_uk', models.CharField(default='Риба яку ми', max_length=120, null=True, verbose_name='Hero: рядок 1 заголовка')),
                ('hero_title_line1_ru', models.CharField(default='Риба яку ми', max_length=120, null=True, verbose_name='Hero: рядок 1 заголовка')),
                ('hero_title_line2', models.CharField(default='робимо самі', max_length=120, verbose_name='Hero: рядок 2 заголовка')),
                ('hero_title_line2_uk', models.CharField(default='робимо самі', max_length=120, null=True, verbose_name='Hero: рядок 2 заголовка')),
                ('hero_title_line2_ru', models.CharField(default='робимо самі', max_length=120, null=True, verbose_name='Hero: рядок 2 заголовка')),
                ('hero_subtitle', models.CharField(default="Коптимо, солимо та в'ялим. Доставляємо по Україні.", max_length=255, verbose_name='Hero: підзаголовок')),
                ('hero_subtitle_uk', models.CharField(default="Коптимо, солимо та в'ялим. Доставляємо по Україні.", max_length=255, null=True, verbose_name='Hero: підзаголовок')),
                ('hero_subtitle_ru', models.CharField(default="Коптимо, солимо та в'ялим. Доставляємо по Україні.", max_length=255, null=True, verbose_name='Hero: підзаголовок')),
                ('hero_image', models.ImageField(blank=True, help_text='Якщо порожньо — використовується стандартне фото з static.', upload_to=src.content.models_home.home_hero_upload_to, verbose_name='Hero: фото')),
                ('hero_image_alt', models.CharField(blank=True, default='Червона та чорна ікра, юкола форелі та копчена скумбрія', max_length=255, verbose_name='Hero: alt фото')),
                ('hero_image_alt_uk', models.CharField(blank=True, default='Червона та чорна ікра, юкола форелі та копчена скумбрія', max_length=255, null=True, verbose_name='Hero: alt фото')),
                ('hero_image_alt_ru', models.CharField(blank=True, default='Червона та чорна ікра, юкола форелі та копчена скумбрія', max_length=255, null=True, verbose_name='Hero: alt фото')),
                ('hero_cta_catalog', models.CharField(default='Перейти до каталогу', max_length=80, verbose_name='Hero: кнопка каталогу')),
                ('hero_cta_catalog_uk', models.CharField(default='Перейти до каталогу', max_length=80, null=True, verbose_name='Hero: кнопка каталогу')),
                ('hero_cta_catalog_ru', models.CharField(default='Перейти до каталогу', max_length=80, null=True, verbose_name='Hero: кнопка каталогу')),
                ('hero_cta_hits', models.CharField(default='Дивитись хіти', max_length=80, verbose_name='Hero: кнопка хітів')),
                ('hero_cta_hits_uk', models.CharField(default='Дивитись хіти', max_length=80, null=True, verbose_name='Hero: кнопка хітів')),
                ('hero_cta_hits_ru', models.CharField(default='Дивитись хіти', max_length=80, null=True, verbose_name='Hero: кнопка хітів')),
                ('hits_title', models.CharField(default='Хіти продажу', max_length=120, verbose_name='Хіти: заголовок')),
                ('hits_title_uk', models.CharField(default='Хіти продажу', max_length=120, null=True, verbose_name='Хіти: заголовок')),
                ('hits_title_ru', models.CharField(default='Хіти продажу', max_length=120, null=True, verbose_name='Хіти: заголовок')),
                ('hits_subtitle', models.CharField(default='Популярні позиції для роздрібного замовлення.', max_length=255, verbose_name='Хіти: підзаголовок')),
                ('hits_subtitle_uk', models.CharField(default='Популярні позиції для роздрібного замовлення.', max_length=255, null=True, verbose_name='Хіти: підзаголовок')),
                ('hits_subtitle_ru', models.CharField(default='Популярні позиції для роздрібного замовлення.', max_length=255, null=True, verbose_name='Хіти: підзаголовок')),
                ('news_title', models.CharField(default='Новинки', max_length=120, verbose_name='Новинки: заголовок')),
                ('news_title_uk', models.CharField(default='Новинки', max_length=120, null=True, verbose_name='Новинки: заголовок')),
                ('news_title_ru', models.CharField(default='Новинки', max_length=120, null=True, verbose_name='Новинки: заголовок')),
                ('news_subtitle', models.CharField(default='Свіжі позиції асортименту.', max_length=255, verbose_name='Новинки: підзаголовок')),
                ('news_subtitle_uk', models.CharField(default='Свіжі позиції асортименту.', max_length=255, null=True, verbose_name='Новинки: підзаголовок')),
                ('news_subtitle_ru', models.CharField(default='Свіжі позиції асортименту.', max_length=255, null=True, verbose_name='Новинки: підзаголовок')),
                ('trust1_title', models.CharField(default='Власне виробництво', max_length=80, verbose_name='Перевага 1: заголовок')),
                ('trust1_title_uk', models.CharField(default='Власне виробництво', max_length=80, null=True, verbose_name='Перевага 1: заголовок')),
                ('trust1_title_ru', models.CharField(default='Власне виробництво', max_length=80, null=True, verbose_name='Перевага 1: заголовок')),
                ('trust1_text', models.CharField(default='Класична технологія копчення та посолу.', max_length=255, verbose_name='Перевага 1: текст')),
                ('trust1_text_uk', models.CharField(default='Класична технологія копчення та посолу.', max_length=255, null=True, verbose_name='Перевага 1: текст')),
                ('trust1_text_ru', models.CharField(default='Класична технологія копчення та посолу.', max_length=255, null=True, verbose_name='Перевага 1: текст')),
                ('trust2_title', models.CharField(default='Доставка НП', max_length=80, verbose_name='Перевага 2: заголовок')),
                ('trust2_title_uk', models.CharField(default='Доставка НП', max_length=80, null=True, verbose_name='Перевага 2: заголовок')),
                ('trust2_title_ru', models.CharField(default='Доставка НП', max_length=80, null=True, verbose_name='Перевага 2: заголовок')),
                ('trust2_text', models.CharField(default='По Україні, оплата за тарифами перевізника.', max_length=255, verbose_name='Перевага 2: текст')),
                ('trust2_text_uk', models.CharField(default='По Україні, оплата за тарифами перевізника.', max_length=255, null=True, verbose_name='Перевага 2: текст')),
                ('trust2_text_ru', models.CharField(default='По Україні, оплата за тарифами перевізника.', max_length=255, null=True, verbose_name='Перевага 2: текст')),
                ('trust3_title', models.CharField(default='Онлайн-оплата', max_length=80, verbose_name='Перевага 3: заголовок')),
                ('trust3_title_uk', models.CharField(default='Онлайн-оплата', max_length=80, null=True, verbose_name='Перевага 3: заголовок')),
                ('trust3_title_ru', models.CharField(default='Онлайн-оплата', max_length=80, null=True, verbose_name='Перевага 3: заголовок')),
                ('trust3_text', models.CharField(default='Безпечна оплата карткою через WayForPay.', max_length=255, verbose_name='Перевага 3: текст')),
                ('trust3_text_uk', models.CharField(default='Безпечна оплата карткою через WayForPay.', max_length=255, null=True, verbose_name='Перевага 3: текст')),
                ('trust3_text_ru', models.CharField(default='Безпечна оплата карткою через WayForPay.', max_length=255, null=True, verbose_name='Перевага 3: текст')),
            ],
            options={
                'verbose_name': 'Головна',
                'verbose_name_plural': 'Головна',
            },
        ),
    ]
