# Generated by Django 5.2.5 on 2026-08-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_homepage_ru_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_blurb',
            field=models.CharField(blank=True, default='Роздрібний інтернет-магазин рибної продукції власного виробництва. Доставка по Україні.', max_length=255, verbose_name='Текст під логотипом у футері'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_blurb_ru',
            field=models.CharField(blank=True, default='Роздрібний інтернет-магазин рибної продукції власного виробництва. Доставка по Україні.', max_length=255, null=True, verbose_name='Текст під логотипом у футері'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_blurb_uk',
            field=models.CharField(blank=True, default='Роздрібний інтернет-магазин рибної продукції власного виробництва. Доставка по Україні.', max_length=255, null=True, verbose_name='Текст під логотипом у футері'),
        ),
    ]
