# Generated by Django 5.2.5 on 2026-08-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(unique=True, verbose_name='Ref (Nova Poshta)')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('area', models.CharField(blank=True, max_length=255, verbose_name='Область')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Синхронізовано')),
            ],
            options={
                'verbose_name': 'Місто (Нова Пошта)',
                'verbose_name_plural': 'Міста (Нова Пошта)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NPWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(unique=True, verbose_name='Ref (Nova Poshta)')),
                ('number', models.CharField(max_length=64, verbose_name='Номер')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Синхронізовано')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='shipping.npcity')),
            ],
            options={
                'verbose_name': 'Відділення (Нова Пошта)',
                'verbose_name_plural': 'Відділення (Нова Пошта)',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttn_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер ТТН')),
                ('shipping_status', models.CharField(choices=[('pending', 'Очікує'), ('created', 'ТТН створено'), ('in_transit', 'В дорозі'), ('delivered', 'Доставлено')], default='pending', max_length=20, verbose_name='Статус доставки')),
                ('tracking_updated_at', models.DateTimeField(blank=True, null=True)),
                ('np_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.npwarehouse')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='commerce.order')),
            ],
            options={
                'verbose_name': 'Відправлення',
                'verbose_name_plural': 'Відправлення',
            },
        ),
    ]
