# Generated by Django 5.2.5 on 2026-08-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npcity',
            options={'ordering': ['name'], 'verbose_name': 'Місто', 'verbose_name_plural': 'Міста'},
        ),
        migrations.AlterModelOptions(
            name='npwarehouse',
            options={'ordering': ['number'], 'verbose_name': 'Відділення', 'verbose_name_plural': 'Відділення'},
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('created', 'ТТН створено'), ('in_transit', 'В дорозі'), ('delivered', 'Доставлено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
